export const AXIOS_TIMEOUT_CODE = "ECONNABORTED";
export const AXIOS_TIMEOUT_ERROR_MESSAGE = "AXIOS_TIMEOUT_ERROR_MESSAGE";
export const API_APP_ERROR_CODE = Object.freeze({
    CANCEL: "CANCEL",
});
